### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by chuprik** [matperez/yii2-unisender#1]
Hello, I have a problem when I do `composer update` or `composer require ...`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package matperez/yii2unisender could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

I have tried use `"matperez/yii2unisender": "~1.0"` and `"matperez/yii2unisender": "*"` but this did not affect. Minimum-stability of my used composer.json is `"dev"`.

Do you know how I can install your extension? :)

**Comment by chuprik** [comment]
Wow. The problem is that you have not published composer.json in http://packagist.com.

**Comment by matperez** [comment]
Ok. Now I've fixed it.

**Comment by chuprik** [comment]
thank you!
